/**
 * Credit Note domain types.
 *
 * A credit note is auto-generated by the `complete_sales_return` RPC when a
 * sales return is completed. The domain type mirrors `credit_notes` in
 * camelCase. Credit notes are read-only from the application layer; they are
 * only created/mutated by the database RPC.
 */

export type CreditNoteStatus = "active" | "applied" | "cancelled";

// ─────────────────────────────────────────────────────────────
// Domain object
// ─────────────────────────────────────────────────────────────

export interface CreditNote {
  readonly id: string;
  readonly organizationId: string;
  readonly creditNoteNumber: string;
  readonly customerId: string;
  readonly invoiceId: string | null;
  readonly salesReturnId: string | null;
  readonly issueDate: Date;
  readonly reason: string | null;
  readonly amount: number;
  readonly status: CreditNoteStatus;
  readonly notes: string | null;
  readonly createdAt: Date;
  readonly updatedAt: Date;
  readonly createdBy: string | null;
}

/** A list row enriched with the joined customer name. */
export interface CreditNoteListItem extends CreditNote {
  readonly customerName: string | null;
}

// ─────────────────────────────────────────────────────────────
// Listing / search
// ─────────────────────────────────────────────────────────────

export type CreditNoteSortField =
  | "credit_note_number"
  | "issue_date"
  | "created_at"
  | "amount";

export interface CreditNoteListParams {
  readonly search?: string;
  readonly status?: CreditNoteStatus;
  readonly customerId?: string;
  readonly page?: number;
  readonly pageSize?: number;
  readonly sortBy?: CreditNoteSortField;
  readonly sortDir?: "asc" | "desc";
}

export interface CreditNoteListResult {
  readonly items: readonly CreditNoteListItem[];
  readonly total: number;
  readonly page: number;
  readonly pageSize: number;
}

// ─────────────────────────────────────────────────────────────
// Result types
// ─────────────────────────────────────────────────────────────

export type CreditNoteErrorCode = "not_found" | "forbidden" | "unknown";

export interface CreditNoteError {
  readonly code: CreditNoteErrorCode;
  readonly message: string;
}

export type CreditNoteActionResult<T = void> =
  | { readonly success: true; readonly data: T }
  | { readonly success: false; readonly error: CreditNoteError };
