/**
 * Sales Return domain types.
 *
 * A sales return is a HEADER (document metadata) plus many LINE ITEMS.
 * Application-level types mirror the DB schema but use camelCase.
 *
 * Completing a return INCREASES stock (goods return to our warehouse from the
 * customer) and REDUCES the customer ledger receivable (a credit on the
 * customer ledger). A credit note is auto-generated by the RPC.
 */

export type SalesReturnStatus = "draft" | "completed" | "cancelled";

export type SalesReturnReason =
  | "damaged"
  | "wrong_product"
  | "expired"
  | "customer_rejection"
  | "warranty"
  | "other";

// ─────────────────────────────────────────────────────────────
// Header
// ─────────────────────────────────────────────────────────────

export interface SalesReturn {
  readonly id: string;
  readonly organizationId: string;
  readonly returnNumber: string;
  readonly invoiceId: string | null;
  readonly customerId: string;
  readonly warehouseId: string | null;
  readonly status: SalesReturnStatus;
  readonly returnDate: Date;
  readonly reason: SalesReturnReason;
  readonly subtotal: number;
  readonly taxAmount: number;
  readonly totalAmount: number;
  readonly notes: string | null;
  readonly createdAt: Date;
  readonly updatedAt: Date;
  readonly createdBy: string | null;
  /** Optimistic-lock counter, auto-incremented by the `handle_updated_at` trigger. */
  readonly version?: number;
}

// ─────────────────────────────────────────────────────────────
// Line item
// ─────────────────────────────────────────────────────────────

export interface SalesReturnItem {
  readonly id: string;
  readonly organizationId: string;
  readonly salesReturnId: string;
  readonly productId: string;
  readonly quantity: number;
  readonly unitPrice: number;
  readonly taxRate: number;
  readonly taxAmount: number;
  readonly lineTotal: number;
  readonly batchId: string | null;
  readonly createdAt: Date;
  readonly createdBy: string | null;
}

/** Header + its line items — the canonical "full" sales return shape. */
export interface SalesReturnWithItems extends SalesReturn {
  readonly items: readonly SalesReturnItem[];
}

/** A list row enriched with the joined customer name. */
export interface SalesReturnListItem extends SalesReturn {
  readonly customerName: string | null;
}

// ─────────────────────────────────────────────────────────────
// Inputs / commands
// ─────────────────────────────────────────────────────────────

export interface CreateSalesReturnItemInput {
  readonly productId: string;
  readonly quantity: number;
  readonly unitPrice: number;
  readonly taxRate?: number;
  readonly batchId?: string;
}

export interface CreateSalesReturnInput {
  readonly returnNumber?: string;
  readonly invoiceId?: string;
  readonly customerId: string;
  readonly warehouseId?: string;
  readonly returnDate?: string;
  readonly reason: SalesReturnReason;
  readonly notes?: string;
  readonly items: readonly CreateSalesReturnItemInput[];
}

/** Update replaces the whole document (header + items); same shape as create. */
export type UpdateSalesReturnInput = CreateSalesReturnInput;

// ─────────────────────────────────────────────────────────────
// Listing / search
// ─────────────────────────────────────────────────────────────

export type SalesReturnSortField =
  | "return_number"
  | "return_date"
  | "created_at"
  | "total_amount";

export interface SalesReturnListParams {
  readonly search?: string;
  readonly status?: SalesReturnStatus;
  readonly customerId?: string;
  readonly page?: number;
  readonly pageSize?: number;
  readonly sortBy?: SalesReturnSortField;
  readonly sortDir?: "asc" | "desc";
}

export interface SalesReturnListResult {
  readonly items: readonly SalesReturnListItem[];
  readonly total: number;
  readonly page: number;
  readonly pageSize: number;
}

// ─────────────────────────────────────────────────────────────
// Result types
// ─────────────────────────────────────────────────────────────

export type SalesReturnErrorCode =
  | "not_found"
  | "forbidden"
  | "validation"
  | "invalid_status"
  | "insufficient_stock"
  | "conflict"
  | "unknown";

export interface SalesReturnError {
  readonly code: SalesReturnErrorCode;
  readonly message: string;
}

export type SalesReturnActionResult<T = void> =
  | { readonly success: true; readonly data: T }
  | { readonly success: false; readonly error: SalesReturnError };
